stages:
  - build

.build: &build
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - export system=$( echo ${CI_JOB_NAME} | awk '{print $2}' )
    - export version=$( echo ${CI_JOB_NAME} | awk '{print $3}' )
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build  -f ${system}-${version}/Dockerfile -t ${CI_REGISTRY_IMAGE}/${system}:${version} .
    - docker push ${CI_REGISTRY_IMAGE}/${system}:${version}
  only:
    - master

build ubuntu 16.04: *build
build ubuntu 18.04: *build
build debian 8: *build
build debian 9: *build
build centos 7: *build

